name: Build and Deploy Angular
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4

      - name: Setup Node ğŸŸ¢
        uses: actions/setup-node@v4
        with:
          node-version: 22 # Angular 21 runs best on Node 22
          cache: 'npm'

      - name: Install Dependencies ğŸ“¦
        run: npm ci --legacy-peer-deps

      - name: Run Unit Tests ğŸ§ª
        # We use the standard Angular command. 
        # --watch=false ensures it runs once and exits (required for CI).
        run: npx ng test --watch=false

      - name: Build App ğŸ”§
        run: |
          # 1. Build using your repo name as the base-href
          npx ng build --configuration production --base-href /angular-ci-cd/
          
          # 2. Fix GitHub Pages routing (404.html trick)
          # We use 'my-github-app' because that is the project name in your angular.json
          cp dist/my-github-app/browser/index.html dist/my-github-app/browser/404.html

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          # âš ï¸ This path matches the output in your angular.json
          folder: dist/*/browser