name: Build and Deploy Angular
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4

      - name: Setup Node ğŸŸ¢
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install Dependencies ğŸ“¦
        run: npm ci --legacy-peer-deps

      - name: Run Unit Tests ğŸ§ª
        run: npx ng test --watch=false

      - name: Build App ğŸ”§
        run: |
          npx ng build --configuration production --base-href /angular-ci-cd/

      - name: Smart Deploy Prep ğŸ§ 
        run: |
          # 1. Create a clean folder for deployment
          mkdir -p dist/deployment

          # 2. FIND the folder containing index.html (Recursive search)
          # This command hunts down 'index.html' inside 'dist' and gets its parent folder
          BUILD_FOLDER=$(find dist -type f -name index.html | head -n 1 | xargs dirname)
          
          echo "âœ… Found build artifact at: $BUILD_FOLDER"
          
          # 3. Copy contents from that discovered folder to our deploy folder
          cp -r $BUILD_FOLDER/* dist/deployment/
          
          # 4. Create the 404 hack
          cp dist/deployment/index.html dist/deployment/404.html

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist/deployment